api-base:
  host: localhost
  port: 8080

spring:
  profiles:
    active: 'dev'
  application:
    name: mte-gateway
  main:
    banner-mode: "off"
logging:
  level:
    root: warn
    ru.danilkaspirin.mtegateway: INFO
    org.springframework.cloud.gateway: DEBUG
  file:
    path: logs/app

#Routes
---
spring:
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://${api-base.host}:${api-base.port}
          predicates:
            - Path=/api/v1/**
        - id: resources
          uri: http://${api-base.host}:${api-base.port}
          predicates:
            - Path=/resources/**