name: Create MTE api base container and deploy to Dockerhub

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mte-api-base/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: 'mte-api-base'
    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v3
    - 
      name: Set Up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'
        cache: 'maven'
    - 
      name: Build MTE api base
      run: |
        cd ./mte-api-base
        mvn -B clean package -DskipTests
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./mte-api-base
        file: ./mte-api-base/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest
