name: Build MTE frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mte-frontend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: 'mte-frontend'
    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./mte-frontend
        file: ./mte-frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest
