name: Build & Test MTE gateway

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mte-gateway/**'
      - '.github/workflows/gateway-build-and-test.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mte-gateway/**'
      - '.github/workflows/gateway-build-and-test.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./mte-gateway
    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v3
    - 
      name: Set Up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'
        cache: 'maven'
    - 
      name: Build
      run: mvn -B clean verify
      working-directory: ${{env.working-directory}}
    - 
      name: Test Report
      run: mvn -B test
      working-directory: ${{env.working-directory}}
