name: Jira ticket transition

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Extract Jira ticket number
        id: extract_issue
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:%B)
          TICKET_ID=$(echo "$COMMIT_MSG" | grep -oP '(?<=Jira: )[A-Z]+-[0-9]+')
          if [ -n "$TICKET_ID" ]; then
            echo "Jira ticket number: $TICKET_ID . This ticket will be transition to done."
            echo "::set-output name=TICKET_ID::$TICKET_ID"
          else
            echo "Jira Ticket wasn't found in commit message"
            exit 1
          fi

      - name: Transition issue
        if: ${{ success() }}
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.extract_issue.outputs.TICKET_ID }}
          transition: "Готово"